@baseUrl = https://<your-api-key>.rest.akismet.com/1.1

###

// It should return `false` for valid comment (e.g. ham).
POST {{baseUrl}}/comment-check
Content-Type: application/x-www-form-urlencoded

blog=https%3A%2F%2Fdocs.belin.io%2Fakismet.js&comment_author=Akismet&comment_author_url=https%3A%2F%2Fdocs.belin.io%2Fakismet.js&comment_content=I'm%20testing%20out%20the%20Service%20API.&comment_type=comment&is_test=true&referrer=https%3A%2F%2Fwww.npmjs.com%2Fpackage%2F%40cedx%2Fakismet&user_agent=Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64%3B%20rv%3A70.0)%20Gecko%2F20100101%20Firefox%2F70.0&user_ip=192.168.0.1&user_role=administrator

###

// It should return `true` for invalid comment (e.g. spam).
POST {{baseUrl}}/comment-check
Content-Type: application/x-www-form-urlencoded

blog=https%3A%2F%2Fdocs.belin.io%2Fakismet.js&comment_author=viagra-test-123&comment_content=Spam!&comment_type=trackback&comment_author_email=akismet-guaranteed-spam%40example.com&is_test=true&user_ip=127.0.0.1&user_agent=Spam%20Bot%2F6.6.6
