@baseUrl = https://rest.akismet.com/1.1

### Checks the specified ham against the service database.
POST {{baseUrl}}/comment-check
Content-Type: application/x-www-form-urlencoded

api_key={{$processEnv AKISMET_API_KEY}}
&blog=https://github.com/cedx/akismet.js
&comment_author=Akismet
&comment_author_url=https://cedric-belin.fr
&comment_content=I'm testing out the Service API.
&comment_type=comment
&is_test=true
&referrer=https://www.npmjs.com/package/@cedx/akismet
&user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
&user_ip=192.168.0.1
&user_role=administrator

### Checks the specified spam against the service database.
POST {{baseUrl}}/comment-check
Content-Type: application/x-www-form-urlencoded

api_key={{$processEnv AKISMET_API_KEY}}
&blog=https://github.com/cedx/akismet.js
&comment_author=viagra-test-123
&comment_content=Spam!
&comment_type=trackback
&comment_author_email=akismet-guaranteed-spam%40example.com
&is_test=true
&user_ip=127.0.0.1
&user_agent=Spam Bot/6.6.6
