@apiUrl = https://rest.akismet.com

### Submits the specified comment that was incorrectly marked as spam but should not have been.
POST {{apiUrl}}/1.1/submit-ham
Content-Type: application/x-www-form-urlencoded

api_key={{$processEnv AKISMET_API_KEY}}
&blog=https://github.com/cedx/akismet.js
&comment_author=Akismet
&comment_author_url=https://cedric-belin.fr
&comment_content=I'm testing out the Service API.
&comment_type=comment
&is_test=true
&referrer=https://www.npmjs.com/package/@cedx/akismet
&user_agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
&user_ip=192.168.0.1
&user_role=administrator
