name: Build the documentation
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: 3.12
      - name: Install dependencies
        run: pip install mkdocs-material mkdocs-git-committers-plugin-2 mkdocs-git-revision-date-localized-plugin
      - name: Deploy documentation
        run: mkdocs gh-deploy --config-file=etc/mkdocs.yaml --force
